DEBUG = false


-- Balloon
BALLOON_RADIUS = 50
BALLOON_HEIGHT = 100 --pixels above bottom of content area


-- Bubble
BUBBLE_RADIUS = 35
DELAY_FACTOR = 15  -- lower is slower
BUBBLE_WEIGHT = 1
BUBBLE_INPUT_SCALAR = 1.3

-- Background
BG_CHANGE_SPEED = .999
BG_CHANGE_UPDATE_RATE = 3000 --ms

-- Obstacles
OBS_FALL_SPEED = 2
OBS_SLEEP_SPEED = 180
OBS_REGULAR_DENSITY = 5
OBS_LIGHT_DENSITY = 2
OBS_HEAVY_DENSITY = 10
OBS_LESS_FRICTION = 0.2
OBS_REGULAR_FRICTION = 0.5
OBS_MORE_FRICTION = 0.8




-- Game
END_TRANSITION_DURATION = 1000 --ms